// Programming: Principles and Practice Using C++ - 3rd Edition
// by Bjarne Stroustrup
//
// Chapter 3
// Exercise 7
// Page 80
// Make a vector holding the ten string values "zero", "one", ..., "nine".
// Use that in a program that converts a digit to its corresponding spelled-out
// numbers into their digit form; e.g., the input 7 gives the output seven.
// Have the same program, using the same input loop, convert spelled-out
// numbers into their digit form; e.g. the input seven gives 7.
//
// This solution is generated by Chat-GPT
#define DEBUG

// Only use modules if supported by the compiler
#if __cpp_modules
import std;
#else
#include "PPPheaders.h"
#endif

int main() {
  vector<string> numbers = {"zero", "one", "two",   "three", "four",
                            "five", "six", "seven", "eight", "nine"};
  string input;

  cout << "Enter a digit (0-9) or a spelled-out number: ";

  while (cin >> input) {
    // Try converting from digit to supported
    if (isdigit(input[0]) && input.size() == 1) {
      int digit = input[0] - '0';

      cout << "Spelled-out: " << numbers[digit] << endl;
    } else {
      // Try converting from word to digit
      auto it = find(numbers.begin(), numbers.end(), input);

      if (it != numbers.end()) {
        cout << "Digit: " << distance(numbers.begin(), it) << endl;
      } else {
        cout << "Invalid input!" << endl;
      }
    }

    cout << "Enter another digit or spelled-out number (Ctrl+C to exit): ";
  }

  return 0;
}
