// Programming: Principles and Practice Using C++ - 3rd Edition
// by Bjarne Stroustrup
//
// Chapter 3
// Exercise 8
// Page 80
// Modify the "mini calculator" from exercise 6 to accept (just) single-digit
// numbers written as either digits or spelled out.
//
// This solution is generated by Chat-GPT
#include <cctype>
#include <limits>
#define DEBUG

// Only use modules if supported by the compiler
#if __cpp_modules
import std;
#else
#include "PPPheaders.h"
#endif

string toLower(const string &str) {
  string lowerStr = str;
  transform(lowerStr.begin(), lowerStr.end(), lowerStr.begin(),
            [](unsigned char c) { return tolower(c); });
  return lowerStr;
}

int get_digit(const string &s) {
  string input = toLower(s);
  vector<string> numbers = {"zero", "one", "two",   "three", "four",
                            "five", "six", "seven", "eight", "nine"};

  if (isdigit(input[0]) && input.size() == 1) {
    return input[0] - '0';
  } else {
    // Try converting frmo digit to int
    auto it = find(numbers.begin(), numbers.end(), input);

    if (it != numbers.end()) {
      return distance(numbers.begin(), it);
    } else {
      return numeric_limits<int>::max(); // indicate that an error occurred
    }
  }
}

int main() {
  string num1, num2, op;
  int i1, i2, answer;
  char o;

  while (true) {
    cout << "Enter two single-digit numbers followed by one of these numeric"
         << endl
         << "operators (+, -, *, /). Each number can be entered as a" << endl
         << "single-digit numeric number or a signle-digit number that" << endl
         << "is spelled out (i.e. zero, one, ..., nine). Follow the two" << endl
         << "numbers by a single numeric operator (+, -, *, /). End with"
         << endl
         << "Ctrl+C:" << endl;

    cin >> num1 >> num2 >> op;

    i1 = get_digit(num1);
    if (i1 == numeric_limits<int>::max()) {
      cout << "The 1st token is not a valid digit. Try again." << endl << endl;
      continue;
    }

    i2 = get_digit(num2);
    if (i2 == numeric_limits<int>::max()) {
      cout << "The 2nd token is not a valid digit. Try again." << endl << endl;
      continue;
    }

    if (op.size() == 1) {
      o = op[0];

      switch (o) {
      case '+':
        answer = i1 + i2;
        cout << i1 << " + " << i2 << " = " << answer << endl;
        break;

      case '-':
        answer = i1 - i2;
        cout << i1 << " - " << i2 << " = " << answer << endl;
        break;

      case '*':
        answer = i1 * i2;
        cout << i1 << " * " << i2 << " = " << answer << endl;
        break;

      case '/':
        if (i2 == 0) {
          cout << i1 << " / " << i2 << " Can't compute (division by zero)"
               << endl;
        } else {
          answer = i1 / i2;
          cout << i1 << " / " << i2 << " = " << answer << endl;
          answer = i1 % i2;
          cout << i1 << " % " << i2 << " = " << answer << endl;
        }
        break;

      default:
        cout << "Invalid operator: " << o << endl;
        break;
      }
    }
    cout << "----------" << endl << endl;
  }
}
