// Programming: Principles and Practice Using C++ - 3rd Edition
// by Bjarne Stroustrup
//
// Chapter 3
// Exercise 11
// Page 80
// Write a program that plays the game "Rock, Paper, Scissors." If you are not
// familiar with the game do some research (e.g., on the Web using Google).
// Research is a common task for programmers. Use a switch-statement to solve
// this exercise. Also, the machine should give random answer (i.e., select
// the next rock, paper, or scissors randomly). Real randomness is too hard
// to provide just now, so just build a vecto with a sequence of values to be
// used as "the next value." If you build the vector into the program, it will
// always play the same game, so maybe you should let the user enter some
// values. Try variations to make it less easy for the user to guess which
// move the machine will make next.
//
// I'm changing this to play "Rock, Paper, Scissors, Lizard, Spock"
// Scissors cuts Paper
// Paper covers Rock
// Rock crushes Lizard
// Lizard poisons Spock
// Spock smashes Scissors
// Scissors decapitates Lizard
// Lizard eats Paper
// Paper disproves Spock
// Spock vaporizes Rock
// Rock crushes Scissors
//
// This solution is generated by Chat-GPT
#include <cstdlib>
#include <iterator>
#include <ostream>
#include <random>
// #define DEBUG

// Only use modules if supported by the compiler
#if __cpp_modules
import std;
#else
#include "PPPheaders.h"
#endif

// Instead of following the suggestion to hard code values I asked Chat-GPT
// to write a function that returns a random int between 0 and 2 inclusive
int make_random_choice() {
  static random_device rd;
  static mt19937 gen(rd());
  static uniform_int_distribution<int> dist(0, 4);
  return dist(gen);
}

// Convert string to lower case so we can make case insensetive string
// compairisons
string toLower(const string &str) {
  string lowerStr = str;
  transform(lowerStr.begin(), lowerStr.end(), lowerStr.begin(),
            [](unsigned char c) { return tolower(c); });
  return lowerStr;
}

void who_won(int computer_choice, int human_choice) {
  switch (computer_choice) {
  case 0: // Rock
    switch (human_choice) {
    case 0: // Rock
      cout << "You both choose Rock - Tie" << endl;
      break;
    case 1: // Paper
      cout << "Paper covers Rock - You win!" << endl;
      break;
    case 2: // Scissors
      cout << "Rock crushes Scissors - Computer wins" << endl;
      break;
    case 3: // Lizard
      cout << "Rock crushes Lizard - Computer wins" << endl;
      break;
    default: // Spock
      cout << "Spock vaporizes Rock - You win!" << endl;
    }
    break;

  case 1: // Paper
    switch (human_choice) {
    case 0: // Rock
      cout << "Paper covers Rock - You win!" << endl;
      break;
    case 1: // Paper
      cout << "You both choose Paper - Tie" << endl;
      break;
    case 2: // Scissors
      cout << "Scissors cuts Paper - You win!" << endl;
      break;
    case 3: // Lizard
      cout << "Lizard eats Paper - You win!" << endl;
      break;
    default: // Spock
      cout << "Paper disproves Spock - Computer wins" << endl;
    }
    break;

  case 2: // Scissors
    switch (human_choice) {
    case 0: // Rock
      cout << "Rock crushes Scissors - You win!" << endl;
      break;
    case 1: // Paper
      cout << "Scissors cuts Paper - Computer wins!" << endl;
      break;
    case 2: // Scissors
      cout << "You both choose Scissors - Tie" << endl;
      break;
    case 3: // Lizard
      cout << "Scissors decaptiates Lizard - Computer wins" << endl;
      break;
    default: // Spock
      cout << "Spock smashes Scissors - You win!" << endl;
    }
    break;

  case 3: // Lizard
    switch (human_choice) {
    case 0: // Rock
      cout << "Rock crushes Lizard - You win!" << endl;
      break;
    case 1: // Paper
      cout << "Lizard eats Paper - Computer wins" << endl;
      break;
    case 2: // Scissors
      cout << "Scissors decaptiates Lizard" << endl;
      break;
    case 3: // Lizard
      cout << "You both choose Lizard - Tie" << endl;
      break;
    default: // Spock
      cout << "Lizard poisons Spock" << endl;
    }
    break;

  default: // Spock
    switch (human_choice) {
    case 0: // Rock
      cout << "Spock vaporizes Rock - Computer wins" << endl;
      break;
    case 1: // Paper
      cout << "Paper disproves Spock - You Win!" << endl;
      break;
    case 2: // Scissors
      cout << "Spock smashes Scissors - Computer wins" << endl;
      break;
    case 3: // Lizard
      cout << "Lizard poisons Spock - You win!" << endl;
      break;
    default: // Spock
      cout << "You both choose Spock - Tie" << endl;
    }
  }
}

int main() {
  vector<string> choices = {"rock", "paper", "scissors", "lizard", "spock"};

  int computer_choice = 0;
  int human_choice = 0;
  string guess;

  cout << "Please type either rock, paper, scissors, lizard, or spock: ";

  while (cin >> guess) {
    computer_choice = make_random_choice();
#ifdef DEBUG
    cout << "computer_choice = " << computer_choice << endl
         << "human_choice = " << human_choice << endl;
#endif

    guess = toLower(guess);
    auto it = find(choices.begin(), choices.end(), guess);
#ifdef DEBUG
    cout << "guess = " << guess << endl;
#endif

    if (it != choices.end()) {
      human_choice = distance(choices.begin(), it);
#ifdef DEBUG
      cout << "human_choice = " << human_choice << endl;
#endif
    } else {
      cout << "Invalid choice:" << endl
           << "Please enter rock, paper, scissors, lizard, or spock" << endl;
    }

    cout << "Computer choose " << choices[computer_choice] << " and you choose "
         << choices[human_choice] << endl;

    who_won(computer_choice, human_choice);
    cout << "Please type either rock, paper, scissors, lizard, or spock: ";
  }
}
