// Programming: Principles and Practice Using C++ - 3rd Edition
// by Bjarne Stroustrup
//
// Chapter 3
// Exercise 9
// Page 80
// There is an old story that the emperor wanted to thank the inventor of the
// game of chess and asked the invetor to name his reward. The inventor asked
// for one grain of rice for the first square, 2 for the second, 4 fot the
// third, and so on, doubling for each of the 64 squares. That may sound
// modest, but there wasn't that much rice in the empire! Write a program to
// caluculate how many squares are requied to give the inventor at least 1,000
// grains of rice, at least 1,000,000 grains of rice, and at least
// 1,000,000,000 grains. You'll need a loop, of course, and probably an int to
// keep track of the grains on the current square, and an int to keep track of
// the grains on all previous squares. We suggest that you write out the value
// of all your variables for each iteration of the loop so that you can see
// what's going on.
//
// This solution is generated by Chat-GPT
#define DEBUG

// Only use modules if supported by the compiler
#if __cpp_modules
import std;
#else
#include "PPPheaders.h"
#endif

int main() {
  long unsigned int current_payment = 1;
  long unsigned int total_payment = 0;

  // print thousand seperators
  locale loc("");
  cout.imbue(loc);

  for (int i = 1; i <= 64; i++) {
    total_payment += current_payment;

    cout << "Payment #" << i << "=" << current_payment
         << " for a total payment of " << total_payment << endl;

    current_payment *= 2;
  }
}
